version: '3'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "3001:9042"

  cassandra-init:
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./schema.cql:/schema.cql
    command: /bin/bash -c "sleep 30 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  sqs:
    image: graze/sqs-local
    ports:
     - "9324:9324"
    volumes:
      - ./elasticmq.conf:/elasticmq.conf
